package(default_visibility = ["//visibility:public"])

load("//third_party/protobuf/protobuf_3p6p1:protobuf.bzl", "py_proto_library")

proto_library(
  name = "utterance_data",
  srcs = ["utterance_data.proto"],
)

py_proto_library(
  name = "utterance_data_py_pb2",
  srcs = ["utterance_data.proto"],
)
